export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_TOKEN_EXPIRED = 'USER_TOKEN_EXPIRED';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const GET_AUTH_USER_ROLE = 'GET_AUTH_USER_ROLE';
export const GET_AUTH_USER_ROLE_SUCCESS = 'GET_AUTH_USER_ROLE_SUCCESS';
export const AD_LOGIN = 'AD_LOGIN'; //AD = Active Directory
export const SET_USER_SOCKET_ID = 'SET_USER_SOCKET_ID';
export const   VERIFY_OTP= 'VERIFY_OTP';
export const   RESEND_OTP= 'RESEND_OTP';
